<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.jetlinks.pro</groupId>
        <artifactId>jetlinks-project-template</artifactId>
        <version>2.11.0-SNAPSHOT</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <name>JetLinks Bootstrap</name>
    <description>单体方式运行JetLinks</description>

    <artifactId>bootstrap</artifactId>

    <properties>
        <jetlinks.ui.version>2.10.0-SNAPSHOT</jetlinks.ui.version>
    </properties>

    <profiles>
        <profile>
            <id>cassandra</id>
            <dependencies>
                <dependency>
                    <groupId>org.jetlinks.pro</groupId>
                    <artifactId>cassandra-component</artifactId>
                    <version>${project.version}</version>
                </dependency>
            </dependencies>
        </profile>

        <profile>
            <id>mongodb</id>
            <dependencies>
                <dependency>
                    <groupId>org.springframework.boot</groupId>
                    <artifactId>spring-boot-starter-data-mongodb-reactive</artifactId>
                </dependency>
            </dependencies>
        </profile>

        <profile>
            <id>oracle</id>
            <dependencies>
                <dependency>
                    <groupId>com.oracle.database.jdbc</groupId>
                    <artifactId>ojdbc11</artifactId>
                    <version>23.7.0.25.01</version>
                </dependency>
            </dependencies>
        </profile>

        <profile>
            <id>sqlserver</id>
            <dependencies>
                <dependency>
                    <groupId>com.microsoft.sqlserver</groupId>
                    <artifactId>mssql-jdbc</artifactId>
                    <version>8.2.2.jre8</version>
                </dependency>
            </dependencies>
        </profile>

        <profile>
            <id>mariaDB</id>
            <dependencies>
                <dependency>
                    <groupId>org.mariadb.jdbc</groupId>
                    <artifactId>mariadb-java-client</artifactId>
                    <version>3.5.3</version>
                </dependency>
                <dependency>
                    <groupId>org.mariadb</groupId>
                    <artifactId>r2dbc-mariadb</artifactId>
                    <version>1.3.0</version>
                </dependency>
            </dependencies>
        </profile>

        <!--
           达梦数据库支持,
           spring:
               r2dbc:
                   url: r2dbc:jdbc:dm://localhost:5236/jetlinks
                   username: SYSDBA
                   password: SYSDBA001
            easyorm:
              default-schema: SYSDBA
              dialect: oracle
        -->
        <profile>
            <id>dameng</id>
            <dependencies>
                <dependency>
                    <groupId>org.jetlinks</groupId>
                    <artifactId>jdbc-bridge-r2dbc-dm</artifactId>
                    <version>1.1.0-SNAPSHOT</version>
                </dependency>
            </dependencies>
        </profile>

        <profile>
            <id>jdbc</id>
            <dependencies>
                <dependency>
                    <groupId>org.postgresql</groupId>
                    <artifactId>postgresql</artifactId>
                </dependency>

                <dependency>
                    <groupId>com.microsoft.sqlserver</groupId>
                    <artifactId>mssql-jdbc</artifactId>
                </dependency>

                <dependency>
                    <groupId>com.oracle.database.jdbc</groupId>
                    <artifactId>ojdbc8</artifactId>
                </dependency>

                <dependency>
                    <groupId>com.mysql</groupId>
                    <artifactId>mysql-connector-j</artifactId>
                    <exclusions>
                        <exclusion>
                            <groupId>com.google.protobuf</groupId>
                            <artifactId>protobuf-java</artifactId>
                        </exclusion>
                    </exclusions>
                </dependency>
            </dependencies>
        </profile>
        <profile>
            <id>es7x</id>
            <properties>
                <elasticsearch.version>7.17.26</elasticsearch.version>
            </properties>

            <activation>
                <activeByDefault>true</activeByDefault>
            </activation>
            <dependencies>

                <dependency>
                    <groupId>org.jetlinks.pro</groupId>
                    <artifactId>elasticsearch-7x</artifactId>
                </dependency>

                <dependency>
                    <groupId>co.elastic.clients</groupId>
                    <artifactId>elasticsearch-java</artifactId>
                    <version>${elasticsearch.version}</version>
                </dependency>

                <dependency>
                    <groupId>org.elasticsearch.client</groupId>
                    <artifactId>elasticsearch-rest-client</artifactId>
                    <version>${elasticsearch.version}</version>
                </dependency>

            </dependencies>
        </profile>

        <profile>
            <id>es8x</id>
            <dependencies>
                <dependency>
                    <groupId>org.jetlinks.pro</groupId>
                    <artifactId>elasticsearch-8x</artifactId>
                </dependency>
            </dependencies>
        </profile>
        <profile>
            <id>timescaledb</id>
            <dependencies>
                <dependency>
                    <groupId>org.jetlinks.pro</groupId>
                    <artifactId>timescaledb-component</artifactId>
                </dependency>
            </dependencies>
        </profile>

        <profile>
            <id>ui</id>
            <dependencies>
                <dependency>
                    <groupId>org.jetlinks.ui</groupId>
                    <artifactId>jetlinks-ui-resource</artifactId>
                    <version>${jetlinks.ui.version}</version>
                </dependency>

                <dependency>
                    <groupId>org.jetlinks.ui</groupId>
                    <artifactId>authentication-manager</artifactId>
                    <version>${jetlinks.ui.version}</version>
                </dependency>

                <dependency>
                    <groupId>org.jetlinks.ui</groupId>
                    <artifactId>datasource-manager</artifactId>
                    <version>${jetlinks.ui.version}</version>
                </dependency>

                <dependency>
                    <groupId>org.jetlinks.ui</groupId>
                    <artifactId>device-manager</artifactId>
                    <version>${jetlinks.ui.version}</version>
                </dependency>

                <dependency>
                    <groupId>org.jetlinks.ui</groupId>
                    <artifactId>data-collector</artifactId>
                    <version>${jetlinks.ui.version}</version>
                </dependency>

                <dependency>
                    <groupId>org.jetlinks.ui</groupId>
                    <artifactId>rule-engine-manager</artifactId>
                    <version>${jetlinks.ui.version}</version>
                </dependency>

                <dependency>
                    <groupId>org.jetlinks.ui</groupId>
                    <artifactId>visualization-manager</artifactId>
                    <version>${jetlinks.ui.version}</version>
                </dependency>

                <dependency>
                    <groupId>org.jetlinks.ui</groupId>
                    <artifactId>jetlinks-media</artifactId>
                    <version>${jetlinks.ui.version}</version>
                </dependency>
            </dependencies>
        </profile>

        <!-- 云边协同 云端管理模块  (选配) -->
        <profile>
            <id>edge</id>
            <dependencies>
                <dependency>
                    <groupId>org.jetlinks.pro</groupId>
                    <artifactId>edge-master</artifactId>
                    <version>${jetlinks.pro.version}</version>
                </dependency>
            </dependencies>
        </profile>

        <!-- 云边协同 云端视频模块  (选配) -->
        <profile>
            <id>edge-media</id>
            <dependencies>
                <dependency>
                    <groupId>org.jetlinks.pro</groupId>
                    <artifactId>edge-media-master</artifactId>
                    <version>${jetlinks.pro.version}</version>
                </dependency>
            </dependencies>
        </profile>

        <!-- 云端录像模块 (选配) -->
        <profile>
            <id>media-recorder</id>
            <dependencies>
                <dependency>
                    <groupId>org.jetlinks.pro</groupId>
                    <artifactId>media-recorder</artifactId>
                    <version>${jetlinks.pro.version}</version>
                </dependency>
            </dependencies>
        </profile>

    </profiles>

    <build>
        <finalName>application</finalName>
        <resources>
            <resource>
                <directory>src/main/resources</directory>
                <filtering>true</filtering>
            </resource>
        </resources>
        <plugins>
            <plugin>
                <artifactId>maven-install-plugin</artifactId>
                <configuration>
                    <skip>true</skip>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-deploy-plugin</artifactId>
                <configuration>
                    <skip>true</skip>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <configuration>
                    <mainClass>org.jetlinks.pro.standalone.JetLinksApplication</mainClass>
                    <layout>ZIP</layout>
                    <layers>
                        <enabled>true</enabled>
                    </layers>
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>repackage</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>

            <plugin>
                <groupId>org.jacoco</groupId>
                <artifactId>jacoco-maven-plugin</artifactId>
                <version>0.8.7</version>
                <executions>
                    <execution>
                        <id>report-aggregate</id>
                        <phase>test</phase>
                        <goals>
                            <goal>report-aggregate</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>

        </plugins>
    </build>

    <dependencies>

        <dependency>
            <groupId>org.jetlinks.pro</groupId>
            <artifactId>common-component</artifactId>
        </dependency>

        <dependency>
            <groupId>org.jetlinks.pro</groupId>
            <artifactId>datasource-manager</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>org.jetlinks.pro</groupId>
            <artifactId>kafka-component</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>org.jetlinks.pro</groupId>
            <artifactId>rabbitmq-component</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-pool2</artifactId>
        </dependency>

        <dependency>
            <groupId>io.projectreactor</groupId>
            <artifactId>reactor-tools</artifactId>
        </dependency>

        <dependency>
            <groupId>${project.groupId}</groupId>
            <artifactId>dashboard-component</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>${project.groupId}</groupId>
            <artifactId>gateway-component</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>org.jetlinks.pro</groupId>
            <artifactId>protocol-component</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>org.jetlinks.pro</groupId>
            <artifactId>rule-engine-manager</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>org.jetlinks.pro</groupId>
            <artifactId>logging-manager</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>org.jetlinks.pro</groupId>
            <artifactId>authentication-manager</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>org.jetlinks.pro</groupId>
            <artifactId>network-manager</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>org.jetlinks.pro</groupId>
            <artifactId>device-manager</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>org.jetlinks.pro</groupId>
            <artifactId>geo-component</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>org.jetlinks.pro</groupId>
            <artifactId>notify-manager</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>org.jetlinks.pro</groupId>
            <artifactId>notify-dingtalk</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>org.jetlinks.pro</groupId>
            <artifactId>notify-wechat</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>org.jetlinks.pro</groupId>
            <artifactId>notify-webhook</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>org.jetlinks</groupId>
            <artifactId>jetlinks-supports</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-redis</artifactId>
        </dependency>

        <!--        <dependency>-->
        <!--            <groupId>org.springframework.boot</groupId>-->
        <!--            <artifactId>spring-boot-starter-actuator</artifactId>-->
        <!--        </dependency>-->

        <dependency>
            <groupId>io.micrometer</groupId>
            <artifactId>micrometer-core</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-r2dbc</artifactId>
        </dependency>


        <dependency>
            <groupId>io.asyncer</groupId>
            <artifactId>r2dbc-mysql</artifactId>
        </dependency>

        <dependency>
            <groupId>org.postgresql</groupId>
            <artifactId>r2dbc-postgresql</artifactId>
        </dependency>

        <dependency>
            <groupId>io.projectreactor.netty</groupId>
            <artifactId>reactor-netty</artifactId>
            <scope>compile</scope>
        </dependency>

        <dependency>
            <groupId>io.r2dbc</groupId>
            <artifactId>r2dbc-h2</artifactId>
        </dependency>

        <dependency>
            <groupId>org.hswebframework.web</groupId>
            <artifactId>hsweb-authorization-basic</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-webflux</artifactId>
        </dependency>

        <!--        <dependency>-->
        <!--            <groupId>org.elasticsearch.client</groupId>-->
        <!--            <artifactId>elasticsearch-rest-high-level-client</artifactId>-->
        <!--        </dependency>-->

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter</artifactId>
        </dependency>

        <dependency>
            <groupId>org.hswebframework.web</groupId>
            <artifactId>hsweb-starter</artifactId>
        </dependency>

        <dependency>
            <groupId>org.hswebframework.web</groupId>
            <artifactId>hsweb-system-file</artifactId>
        </dependency>

        <dependency>
            <groupId>org.hswebframework.web</groupId>
            <artifactId>hsweb-system-dictionary</artifactId>
        </dependency>

        <dependency>
            <groupId>org.hswebframework.web</groupId>
            <artifactId>hsweb-access-logging-aop</artifactId>
        </dependency>

        <dependency>
            <groupId>de.ruedigermoeller</groupId>
            <artifactId>fst</artifactId>
        </dependency>

        <dependency>
            <groupId>org.jetlinks.pro</groupId>
            <artifactId>influxdb-component</artifactId>
        </dependency>

        <dependency>
            <groupId>org.jetlinks.pro</groupId>
            <artifactId>tdengine-component</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>org.jetlinks.pro</groupId>
            <artifactId>clickhouse-component</artifactId>
        </dependency>

        <dependency>
            <groupId>org.jetlinks.pro</groupId>
            <artifactId>jetlinks-function</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>org.jetlinks.pro</groupId>
            <artifactId>visualization-manager</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>org.jetlinks.pro</groupId>
            <artifactId>media-manager</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>org.springdoc</groupId>
            <artifactId>springdoc-openapi-starter-webflux-ui</artifactId>
        </dependency>

        <dependency>
            <groupId>com.github.xiaoymin</groupId>
            <artifactId>knife4j-openapi3-ui</artifactId>
            <version>4.5.0</version>
        </dependency>



    </dependencies>

</project>
