# 注意!!!,本地开发时,请创建application-local.yml文件进行配置,不要随意修改application-default.yml文件.


# 集群配置,请确保集群节点间的以下HOST和PORT能够互相访问到.
CLUSTER_EXTERNAL_HOST: 127.0.0.1 # 集群间其他节点访问本节点的地址
CLUSTER_EXTERNAL_PORT: ${jetlinks.cluster.port} # 1{server.port}

RPC_EXTERNAL_HOST: ${CLUSTER_EXTERNAL_HOST} # 集群间当前节点对外提供RPC通信的地址
RPC_EXTERNAL_PORT: 2${server.port} # 集群间当前节点对外提供RPC通信的端口

# 集群种子节点地址,多个地址用逗号分隔,通常为api-gateway-service的{CLUSTER_EXTERNAL_HOST:CLUSTER_EXTERNAL_PORT}
CLUSTER_SEEDS: 127.0.0.1:18800

RPC_TOKEN: J@t1iNksR9~